---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  name: jaeger-product
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: LOG-LEVEL
        value: debug
      - name: KAFKA-PROVISIONING-MINIMAL
        value: "true"